// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_jRhLPTDhpoYv6njwKhflOzWTCM5zooI',
    appId: '1:787240437833:web:e02fbaa6116b91b6911798',
    messagingSenderId: '787240437833',
    projectId: 'guideon-f34a6',
    authDomain: 'guideon-f34a6.firebaseapp.com',
    storageBucket: 'guideon-f34a6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbP75Dh0QsuCfvqWpSCoX80gL3_ZTqLbw',
    appId: '1:787240437833:android:79f5da2c0f3a0b4a911798',
    messagingSenderId: '787240437833',
    projectId: 'guideon-f34a6',
    storageBucket: 'guideon-f34a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7Fp6SVx-U97WxK-ykcFTuo1PQYgwyyZU',
    appId: '1:787240437833:ios:747d7ec112539bb9911798',
    messagingSenderId: '787240437833',
    projectId: 'guideon-f34a6',
    storageBucket: 'guideon-f34a6.firebasestorage.app',
    iosBundleId: 'com.example.guideon',
  );
}
